#!/bin/bash
#   Automated probabilistic tractography plugin for FSL; first stage.
#
#   Performs tractography as used in De Groot et al., NeuroImage 2013.
#   2013, Marius de Groot
#
#   LICENCE
#
#   AutoPtx, plugin for FSL, Release 0.1 (c) 2013, Erasmus MC, University
#   Medical Center (the "Software")
#
#   The Software remains the property of the Erasmus MC, University Medical
#   Center ("the University").
#
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software, or
#   that it will be suitable for any particular purpose or for use under
#   any specific conditions.  Furthermore, the University disclaims all
#   responsibility for the use which is made of the Software.  It further
#   disclaims any liability for the outcomes arising from using the
#   Software.
#
#   The Licensee agrees to indemnify the University and hold the University
#   harmless from and against any and all claims, damages and liabilities
#   asserted by third parties (including claims for negligence) which arise
#   directly or indirectly from the use of the Software or the sale of any
#   products based on the Software.
#
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University.  The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product.  You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#
#   You are not permitted under this Licence to use this Software
#   commercially.  Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the Software
#   or any derivative of it for research with the final aim of developing
#   software products for sale or license to a third party or (3) use of
#   the Software or any derivative of it for research with the final aim of
#   developing non-software products for sale or license to a third party,
#   or (4) use of the Software to provide any service to an external
#   organisation for which payment is received.  If you are interested in
#   using the Software commercially, please contact the technology transfer
#   company of the University to negotiate a licence.  Contact details are:
#   tto@erasmusmc.nl quoting reference SOPHIA #2013-012 and the
#   accompanying paper DOI: 10.1016/j.neuroimage.2013.03.015.
#

Usage() {
cat << EOF

Usage: autoPtx_1_preproc <image1> <image2> ...

    With 'image1' etc. the DWI data for each subject in a separate dir. Note
    that the directory name should be unique for each subject, and that this
    data will be moved."

    Next to the datafile, the following files are expected to be available:
    - 'bvecs' text file containing bvectors in 'dtifit' format
    - 'bvals' text file containing b-values in 'dtifit' format
    - 'nodif_brain_mask' brain mask image

EOF
    exit 1
}

[ "$1" = "" ] && Usage

mkdir -p preproc

\rm -f preproc/subjectList
for f in `$FSLDIR/bin/imglob $@` ; do

    echo "Processing $f"

    # obtain subject ID
    path=`dirname $f`
    sub=`basename $path`
    echo $sub >> preproc/subjectList

    mkdir -p preproc/$sub
    $FSLDIR/bin/immv $f preproc/$sub/data
    $FSLDIR/bin/immv $path/nodif_brain_mask preproc/$sub/nodif_brain_mask
    \mv $path/bvecs preproc/$sub/bvecs
    \mv $path/bvals preproc/$sub/bvals

    # perform tensor fit to obtain FA image (to obtain std2native warp)
    $FSLDIR/bin/dtifit --sse -k preproc/$sub/data -o preproc/$sub/dti -m preproc/$sub/nodif_brain_mask -r preproc/$sub/bvecs -b preproc/$sub/bvals

    # estimate registration to standard space
    $FSLDIR/bin/fsl_reg preproc/$sub/dti_FA $FSLDIR/data/standard/FMRIB58_FA_1mm preproc/$sub/nat2std -e -FA
    $FSLDIR/bin/invwarp -r preproc/$sub/dti_FA -w preproc/$sub/nat2std_warp -o preproc/$sub/std2nat_warp

    # launch bedpostx
    $FSLDIR/bin/bedpostx preproc/$sub

    # create native space reference volume in 1mm cubic resolution
    $FSLDIR/bin/flirt -in preproc/$sub/dti_FA -ref preproc/$sub/dti_FA -applyisoxfm 1 -out preproc/$sub/refVol
    $FSLDIR/bin/fslmaths preproc/$sub/refVol -mul 0 preproc/$sub/refVol

done

echo "Done. Now launch tractography by running autoPtx_2_launchTractography after "
echo "all BedpostX jobs have finished."
