
%==========================================================================
function [files]=mous_take5(prefix,fctPath,fct_images);
%==========================================================================
% FORMAT: [files]=take5(prefixstatus,prefix,sessionPath,fct_images,flax);
% INPUT: prefix - {''|'r'|'ar'|'war'|'swar'} - determines which files to
% selected; in turn,
% '' - functional;
% 'r' - realignd functionals;
% 'ar' - acqusition time corrected;
% 'war' - normalized;
% 'swar' - spatially filtered;
% sessionPath - cell array of the full session paths generated by the
% function selectimages; fct_images - cell array containing session
% specific cell arrays with functional image names
% OUTPUT: subjectPath - fullpath to the current subject; sessionPath -
% cell array of the full session paths; fct_images - cell array containing
% cell arrays with functional image names; strPath - character array with
% the fullpath to the directory of the structural image;

%--------------------------------------------------------------------------
% Author(s):    kmp, julia
% Updated:      09/07/2008, 19/10/2008, 16/04/2012
% Date:         09/11/2006
% © Karl Magnus Petersson
%--------------------------------------------------------------------------
   
  files={};
  files=cellstr(strcat( ...
      fctPath,filesep,prefix,fct_images));
  files={files};
%--------------------------------------------------------------------------
% OUTPUT - files
%End of take5--------------------------------------------------------------
