function [mri3d, h] = mous_fmri_3dto3d(subjectname, mri, sourcemodel, template, varargin)

spmparams    = ft_getopt(varargin, 'spmparams',    []);
sphereradius = ft_getopt(varargin, 'sphereradius', 5); 

% % get the BOLD data
% filename   = fullfile(params.fmripath, params.fmrifilename);
% mri        = ft_read_mri(filename);
% mri.inside = isfinite(mri.anatomy); % ensure that voxels without data will not be used in the interpolation
% mri.pow    = mri.anatomy; % for one reason or another it does not work if I keep using anatomy for the correct interpolation of NaNs
% mri        = rmfield(mri, 'anatomy');
% mri.coordsys = 'spm';

if ~isfield(mri, 'pow') && isfield(mri, 'anatomy')
  mri.inside = isfinite(mri.anatomy);
  mri.pow    = mri.anatomy;
  mri        = rmfield(mri, 'anatomy');
end
if ~isfield(mri, 'coordsys')
  mri.coordsys = 'spm';
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% first do an inverse warp of the coordinates at which the fMRI is defined
% to go back to the coordinate system defined in the coregMNI volume

% % get the spatial normalization parameters generated by Julia: these
% % operate on SxxxcoregMNI.nii
% filename   = fullfile(params.snpath, params.snfilename);
% spmparams  = load(filename);
if isempty(spmparams)
  % try to guess where to get them
  filename  = fullfile('/home/language/juludd/MOUS/preprocdata/',subjectname,'Structural',[subjectname,'coregMNI_sn.mat']);
  spmparams = load(filename);
end

[x,y,z] = ndgrid(1:mri.dim(1),1:mri.dim(2),1:mri.dim(3));
mripos  = [x(:) y(:) z(:)]; clear x y z;
tmp     = ft_warp_apply(mri.transform, mripos);
mripos  = ft_warp_apply(spmparams, tmp, 'sn2individual');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% next, express the positions in the ctf-convention

% get the original mri that was used for the spatial normalization
mrimni = mous_db_getdata(subjectname, 'meg_anatomy_coregMNI');
mrimni.coordsys = 'spm';

% get the ctf-aligned mri
mrictf = mous_db_getdata(subjectname, 'meg_anatomy_coregCTF');
mrictf.coordsys = 'ctf';

% get the Affine transformation from mni to ctf
T = mrictf.transform/mrimni.transform;

mripos = ft_warp_apply(T, mripos);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% next, we do a forward warp into normalised space using JM's parameters,
% this is a two step procedure, we need an affine transformation first.

cfg           = [];
cfg.nonlinear = 'no';
mrictfn       = ft_volumenormalise(cfg, mrictf);

% Affine matrix that approximately aligns ctf coordinate system with
% MNI-ish coordinate system. Point of departure for the non-linear
% parameter estimation in FT
T2 = mrictfn.initial;

mripos     = ft_warp_apply(T2, mripos);
spmparams2 = sourcemodel.params;
mripos     = ft_warp_apply(spmparams2, mripos, 'individual2sn');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% next, we can proceed to the interpolation. represent the fMRI data as an
% FT source structure, since the positions are now irregularly spaced.

% remove the nans from the mripos (due to the spatial normalization or so I
% guess
inside_orig = mri.inside; 
sel = sum(isfinite(mripos),2)==3;

mrinew.pos = mripos(sel,:);
mrinew.pow = mri.pow(sel);
mrinew.inside  = find(inside_orig(sel));
mrinew.outside = setdiff((1:size(mrinew.pos,1))', mrinew.inside);

template = ft_convert_units(template, 'mm');

cfg              = [];
cfg.parameter    = 'pow';
cfg.interpmethod = 'sphere_weighteddistance';
cfg.sphereradius = sphereradius; 
mri3d            = ft_sourceinterpolate(cfg, mrinew, template); 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Quality checks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% check whether the template grid positions and the mrinew.pos overlap
pos1 = mrinew.pos(mrinew.inside,:);
pos2 = template.pos(template.inside,:);

h=figure;
subplot(2,2,1);hold on;
plot3(pos1(:,1),pos1(:,2),pos1(:,3),'.');
plot3(pos2(:,1),pos2(:,2),pos2(:,3),'r.');
axis equal
subplot(2,2,2);hold on;
plot3(pos1(:,1),pos1(:,2),pos1(:,3),'.');
plot3(pos2(:,1),pos2(:,2),pos2(:,3),'r.');
axis equal;view([0 0]);
subplot(2,2,3);hold on;
plot3(pos1(:,1),pos1(:,2),pos1(:,3),'.');
plot3(pos2(:,1),pos2(:,2),pos2(:,3),'r.');
axis equal;view([90 0]);
