function [mri2d, meg, h] = mous_fmri_3dto2d(subjectname, mri, varargin)

spmparams = ft_getopt(varargin, 'spmparams', []);

% % get the BOLD data
% filename   = fullfile(params.fmripath, params.fmrifilename);
% mri        = ft_read_mri(filename);
% mri.inside = isfinite(mri.anatomy); % ensure that voxels without data will not be used in the interpolation
% mri.pow    = mri.anatomy; % for one reason or another it does not work if I keep using anatomy for the correct interpolation of NaNs
% mri        = rmfield(mri, 'anatomy');
% mri.coordsys = 'spm';

if ~isfield(mri, 'pow') && isfield(mri, 'anatomy')
  mri.inside = isfinite(mri.anatomy);
  mri.pow    = mri.anatomy;
  mri        = rmfield(mri, 'anatomy');
end
if ~isfield(mri, 'coordsys')
  mri.coordsys = 'spm';
end

% % get the spatial normalization parameters generated by Julia: these
% % operate on SxxxcoregMNI.nii
% filename   = fullfile(params.snpath, params.snfilename);
% spmparams  = load(filename);
if isempty(spmparams)
  % try to guess where to get them
  %filename  = fullfile('/home/language/juludd/MOUS/preprocdata/',subjectname,'Structural',[subjectname,'coregMNI_sn.mat']);
  filename  = fullfile('/project/3011020.09/MRI/',subjectname,'mri_anatomy/preprocdata',[subjectname,'coregMNI_sn.mat']);
  spmparams = load(filename);
end

% get the original mri that was used for the spatial normalization
mrimni = mous_db_getdata(subjectname, 'meg_anatomy_coregMNI');
mrimni.coordsys = 'spm';

% get the ctf-aligned mri
mrictf = mous_db_getdata(subjectname, 'meg_anatomy_coregCTF');
mrictf.coordsys = 'ctf';

% get the Affine transformation from ctf to mni
T = mrimni.transform/mrictf.transform;


% this is the normalization that is needed, compute the normalized mri
% for later sanity check
cfg           = [];
cfg.spmparams = spmparams;
mrimnin       = ft_volumenormalise(cfg, mrimni);

% load meg cortical sheet
mous_db_getdata(subjectname,'meg_anatomy_sourcemodel2D_surfreg'); %, rootdir);
meg = ft_convert_units(bnd, 'mm'); clear bnd;

% first warp the positions in the cortical sheet to the correct starting positions (after converting to mm)
pos2d = ft_warp_apply(T, meg.pos);

% transform the meg positions from approximate mni space to normalized mni space, using the sn file
pos2d_sn = ft_warp_apply(spmparams, pos2d, 'individual2sn');
meg.pos  = pos2d_sn;

% detect outsides being a bit lenient
inside_orig = mri.inside;
conn        = conndef(3, 'max');
inside      = imdilate(inside_orig, conn);
inside      = imdilate(inside,      conn);
inside      = imdilate(inside,      conn);
inside      = imdilate(inside,      conn);

tmp         = mri;
tmp.inside  = inside;
tmp.pow     = double(tmp.inside);

cfg              = [];
cfg.parameter    = 'pow'; % yes indeed
cfg.interpmethod = 'nearest';
tmp              = ft_sourceinterpolate(cfg, tmp, meg); % with the nearest interpolation, we get nans where no fMRI data is available
outside          = tmp.pow==0;

% put the original inside back
mri.inside = inside_orig;

cfg.interpmethod = 'nearest';%'sphere_weighteddistance';
cfg.sphereradius = 5; 
mri2d              = ft_sourceinterpolate(cfg, mri, meg); 
mri2d.pow(outside) = nan;
mri2d.inside       = find(outside==0);
mri2d.outside      = find(outside);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Quality checks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% interpolate the fMRI data onto the normalized anatomy for quality checking
cfg              = [];
cfg.parameter    = 'pow';
cfg.interpmethod = 'nearest';
mri_interp       = ft_sourceinterpolate(cfg, mri, mrimnin);

cfg  = [];
cfg.funparameter = 'pow';
cfg.method       = 'slice';
cfg.nslices      = 20;
ft_sourceplot(cfg, mri_interp);
set(gcf,'position',[10 10 1000 1000]);
h(1) = gcf;

% visualize the warped sheet with the normalized anatomy for quality checking
h(2) = figure('position',[10 10 1000 1000]);ft_plot_montage(mrimnin.anatomy,'transform',mrimnin.transform,'intersectmesh',meg,'intersectlinewidth',1);