function mous_bfica_parcellate_statistics_Sevl_genetics(subjects, geneticsinfo, grouping, opt)
% Calculate statistics for parcellate cortical sheet
% cortical sheet created by interpolating from 3D volumetric space (output
% from beamformer)
% Determines whether there is a difference between 
% genetics groups for the SentenceEarly vs. SentenceLate contrast

%% create groups for contrast
if numel(grouping)~=2,
  error('number of groups different from 2 is not allowed');
end

sel = cell(1,2);
for k = 1:numel(grouping)
  if iscell(grouping{k})
    sel{k} = zeros(0,1);
    for m = 1:numel(grouping{k})
      sel{k} = [sel{k}; find(strcmpi({geneticsinfo.genotype}', grouping{k}{m}))];
    end
  else
    sel{k} = find(strcmpi({geneticsinfo.genotype}', grouping{k}));  % use strcmpi, because there's 'Allele X', and 'allele X';
  end
end

group{1} = intersect(subjects, {geneticsinfo(sel{1}).name}');
group{2} = intersect(subjects, {geneticsinfo(sel{2}).name}');

%% Determine input data
% datatfiles
rootdir  = '/project/3011020.09/MEG/';
savedir  = '/project/3011020.09/nielam/groupresults/bfica/visual/context_sentseq/';

savename = 'sourcedata_genetics_Sevl';
sourcedat1 =  '_bfica_sourcedata_lateSEN_matched_strat_';
sourcedat2 = '_bfica_sourcedata_earlySEN_matched_strat_';

% TOI: set timepoints
time = [0.25 0.35 0.45];
tmp = num2str(time*100,'%03d');
toi = [tmp(1:3),'-',tmp(end-2:end),'s'];

% FOI: set frequencies for  loading data
if ismember(opt.freq,2.5:2.5:12.5)
  suff = 'low';
elseif ismember(opt.freq,12:4:32)
  suff = 'medium';
elseif ismember(opt.freq,40:4:100)
  suff = 'high';
end
frqstr = [num2str(opt.freq),'Hz','_'];

% baseline settings
if strcmp(suff,'low')
    bslt = 1;
elseif strcmp(suff,'medium') || strcmp(suff,'high')
    bslt = [1 2];
end

dataformat = 'compressed';

%% create contrasts  (4 conditions:  SentEarlyg1, SentLateg1, SentEarlyg2, SentLateg2)
for gcnt = 1:numel(group)
  for scnt = 1:numel(group{gcnt})
    
    if scnt == 1
      %% FIXME: where is dataformat variable created for use on line 70 in ft_read_cifti.m?
      %  FIX, and then uncomment the lines 70-75, and 78
      tmp1 = ft_read_cifti(fullfile('/project/3011020.09/MEG',group{gcnt}{scnt},'bfica',[group{gcnt}{scnt}, sourcedat1,frqstr,toi,'.ptseries.nii']));
      tmp2 = ft_read_cifti(fullfile('/project/3011020.09/MEG',group{gcnt}{scnt},'bfica',[group{gcnt}{scnt}, sourcedat2,frqstr,toi,'.ptseries.nii']));
      oritime  = tmp1.time;  
      tmp1     = rmfield(tmp1,'brainordinate'); tmp2 = rmfield(tmp2,'brainordinate'); 
    else
      % insert current subject's data (ovewrite previous)
      % mous_cifti_quickread only loads the voxel data (one field), instead of entire data structure
      tmp1.ptseries = mous_cifti_quickread(fullfile('/project/3011020.09/MEG',group{gcnt}{scnt},'bfica',[group{gcnt}{scnt}, sourcedat1 ,frqstr,toi,'.ptseries.nii']));
      tmp1.time = oritime; % otherwise number of timepoinst too short (for each subj changed from w/ baseline to no baseline time point; see code below)
      tmp2.ptseries = mous_cifti_quickread(fullfile('/project/3011020.09/MEG',group{gcnt}{scnt},'bfica',[group{gcnt}{scnt}, sourcedat2 ,frqstr,toi,'.ptseries.nii']));
      tmp2.time = oritime; 
    end 
    %% baseline subtraction
    %%%%% CONDITION SPECIFIC ABSOLUTE BASELINE %%%%%
    if strcmp(opt.bsltype,'abs') 
      % s1
      bsl = mean(tmp1.ptseries(:,bslt),2);  % do subtraction
      dat = tmp1.ptseries - bsl*ones(1,numel(tmp1.time));
      if strcmp(suff,'low')                 % remove baseline timepoints; data points for removal depends on freqrange (which vary in baseline length)
        tmp1.ptseries = dat(:,2:end);
      elseif strcmp(suff,'medium') || strfind(suff,'high')
        tmp1.ptseries = dat(:,3:end);
      end

      % s2
      bsl = mean(tmp2.ptseries(:,bslt),2);
      dat = tmp2.ptseries - bsl*ones(1,numel(tmp2.time));
      if strcmp(suff,'low')
        tmp2.ptseries = dat(:,2:end);
      elseif strcmp(suff,'medium') || regexp(suff,'high')
        tmp2.ptseries = dat(:,3:end);
      end
      tmp1.time = time; tmp2.time = time; 

    %%%%%%% COMMON ABSOLUTE BASELINE %%%%%
    elseif strcmp(opt.bsltype,'comabs')  
      bsl1   = mean(tmp1.ptseries(:,bslt),2);
      bsl2   = mean(tmp2.ptseries(:,bslt),2);
      bslcom = (bsl1+bsl2)/2;

      % s1
      dat = tmp1.ptseries - bslcom*ones(1,numel(tmp1.time));  % remove baseline
      if strcmp(suff,'low')                    % remove baseline timepoints from data
        tmp1.ptseries = dat(:,2:end);
      elseif strcmp(suff,'medium') || strfind(suff,'high')
        tmp1.ptseries = dat(:,3:end);
      end

      % s2
      dat = tmp2.ptseries - bslcom*ones(1,numel(tmp2.time));
      if strcmp(suff,'low')
        tmp2.ptseries = dat(:,2:end);
      elseif strcmp(suff,'medium') || regexp(suff,'high')
        tmp2.ptseries = dat(:,3:end);
      end

      % update time axis after subtraction (default times generated by ft_read_cifti)
      tmp1.time = time; tmp2.time = time;  

    %%%%%% CONDITION SPECIFIC RELATIVE BASELINE %%%%% 
    elseif strcmp(opt.bsltype,'rel')  
      % s1
      bsl = mean(tmp1.ptseries(:,bslt),2);  % do subtraction
      dat = (tmp1.ptseries)./(bsl*ones(1,numel(tmp1.time)));
      if strcmp(suff,'low')                    % remove baseline timepoints
        s1{k}.ptseries = dat(:,2:end);
      elseif strcmp(suff,'medium') || strfind(suff,'high')
        s1{k}.ptseries = dat(:,3:end);
      end

      % s2
      bsl = mean(tmp2.ptseries(:,bslt),2);
      dat = (tmp2.ptseries)./(bsl*ones(1,numel(s2{k}.time)));
      if strcmp(suff,'low')
        tmp2.ptseries = dat(:,2:end);
      elseif strcmp(suff,'medium') || regexp(suff,'high')
        tmp2.ptseries = dat(:,3:end);
      end

      % update time axis after subtraction
      tmp1.time = time; tmp2.time = time;  
    end
    
    %% Set data structure for stats
    % main test
    diff = tmp1;    diff.ptseries = tmp1.ptseries - tmp2.ptseries;
    gendiff{gcnt}{scnt} = diff;
    
    % single conditions for post-hoc test
    if gcnt == 1
      g1late{scnt}  = tmp1;
      g1early{scnt} = tmp2;
    elseif gcnt == 2
      g2late{scnt}  = tmp1;
      g2early{scnt} = tmp2;
    end

    
    %% quantify average and variance 
    if scnt == 1     
      sumlate{gcnt}  = tmp1.ptseries;   % SenLate G1 ; SenLate G2
      sumearly{gcnt} = tmp2.ptseries;   % SenEarly G1; SenEarly G2
      
      ssqlate{gcnt}  = tmp1.ptseries.^2;
      ssqearly{gcnt} = tmp2.ptseries.^2;
    else
      sumlate{gcnt}  = sumlate{gcnt}  + tmp1.ptseries;
      sumearly{gcnt} = sumearly{gcnt} + tmp2.ptseries;
      
      ssqlate{gcnt}  = ssqlate{gcnt}  + tmp1.ptseries.^2;
      ssqearly{gcnt} = ssqearly{gcnt} + tmp2.ptseries.^2;
    end
      
  end   % subject
end   % group

%% compute mean per condition and sem
% var = (ssq-sum.^2./Nsubj)./(Nsubj-1);
% sqrt(var./nsubj)
nsubj{1} = numel(group{1});
nsubj{2} = numel(group{2});

for gcnt = 1:numel(group)
  avglate{gcnt}  = sumlate{gcnt}./nsubj{gcnt};  % avglateG1, avglateG2
  avgearly{gcnt} = sumearly{gcnt}./nsubj{gcnt}; % avgearlyG1, avgearlyG2
  
  varlate{gcnt}  = (ssqlate{gcnt}  - sumlate{gcnt}.^2./nsubj{gcnt})./(nsubj{gcnt}-1);
  varearly{gcnt} = (ssqearly{gcnt} - sumearly{gcnt}.^2./nsubj{gcnt})./(nsubj{gcnt}-1);
  
  semlate{gcnt}  = sqrt(varlate{gcnt}./nsubj{gcnt});  % semlate G1, semlate G2 
  semearly{gcnt} = sqrt(varearly{gcnt}./nsubj{gcnt}); % semearly G1, semearly G2
end

%% statistics

cfg = []; 
cfg.method           = 'montecarlo';
cfg.statistic        = 'indepsamplesT';
cfg.clusterthreshold = 'nonparametric_individual';
cfg.numrandomization = ft_getopt(opt,'numrand',3000);
cfg.correctm         = 'cluster'; % cluster over time, not space
cfg.neighbours       = [];
cfg.alpha            = 0.05;
cfg.correcttail      = 'alpha'; % Each tail will be tested with alpha = 0.025.
cfg.latency          = [time(1) time(3)];
cfg.channel          = opt.roi;
cfg.ivar      = 1;
cfg.parameter = 'ptseries';
cfg.design    = [ones(1,nsubj{1}) ones(1,nsubj{2})*2]; 

% main test
% statgen    = ft_timelockstatistics(cfg,gendiff{1}{:},gendiff{2}{:}); % G1(late-early) vs. G2(late-early)

% posthoc 
% possibilities:
  % Late/Early difference in one group but not the other
  % Direction of L/E difference is different for each group (e.g., L>E for g1, and L<E for g2)
  
  
cfg.statistic = 'depsamplesT';  
cfg.uvar   = 2;
% group1  
cfg.design = [ones(1,nsubj{1}) ones(1,nsubj{1})*2; 1:nsubj{1} 1:nsubj{1}];
statg1lve  = ft_timelockstatistics(cfg,g1late{:},g1early{:}); % lateWL   - earlyWL 

% group2
cfg.design = [ones(1,nsubj{2}) ones(1,nsubj{2})*2; 1:nsubj{2} 1:nsubj{2}];
statg2lve  = ft_timelockstatistics(cfg,g2late{:},g2early{:}); % earlySEN - earlyWL

% if sign(cfg.latency(1)) == -1
%   if ismember(freq,2.5:2.5:12.5)
%     t1 = num2str(cfg.latency(1)*10,'%03d');
%   elseif ismember(freq,12:4:100)
%     t1 = num2str(cfg.latency(1)*100,'%04d');
%   end
% else
%   t1 = num2str(cfg.latency(1)*100,'%03d');
% end
% if numel(cfg.latency) > 1
%   t2 = num2str(cfg.latency(end)*100,'%03d');
%   toiall = [t1,'-',t2];
% else
%   toiall = [t1,'s'];
% end


%% save
tnsubj = num2str(nsubj{1}+nsubj{2});
save([savedir,savename,'_',frqstr,'_',geneticsinfo.snp,'_',toi,'_',bsltype,'_',tnsubj,'subj.mat'],...
       'statgen','statg1lve','statg2lve','nsubj',...
       'avglate','avgearly','semlate','semearly','-v7.3');
     

end
