% This script extracts the SubjectName, QuestionNr and responses logfiles
% generated by presentation in the fMRI and MEG scans for stimuli presented
% in the auditory domain

% Output matrix [SingleTrialResponse_vis_meg] has the following columns
% 1  subj
% 2  response (1 = wrong, 0 = correct)
% 3  sentence (.wav filename)
% 4  sentence type (RCsent, MXsent, RCseq, MXseq)
% sentence type:   1 = sentRC;  2 = sentMX, 3 = sequenceRC, 4 = sequenceMX

% Output matrix [grpdesc] holds the mean and standard deviation for all
% sentences (i.e. all sentence types) across subjects

% output matrix [sp] sorts data into the 4 types of sentences (see
% description in code) to be used for further analysis in SPSS

% not the most efficient script, but it is accurate

% nielam 11.11.2014

%% Get responses for single trials
subjectname= {'A2002' 'A2003' 'A2004' 'A2005' 'A2006' 'A2007' 'A2008' 'A2009'...
'A2010' 'A2011' 'A2013' 'A2014' 'A2015' 'A2016' 'A2017' 'A2019'...
'A2020' 'A2021' 'A2024' 'A2025' 'A2027' 'A2028' 'A2029'...
'A2030' 'A2031' 'A2032' 'A2033' 'A2034' 'A2035' 'A2036' 'A2037' 'A2038' 'A2039'...
'A2040' 'A2041' 'A2042' 'A2046' 'A2047' 'A2049'...
'A2050' 'A2051' 'A2052' 'A2053' 'A2055' 'A2056' 'A2057' 'A2058' 'A2059'...
'A2061' 'A2062' 'A2063' 'A2064' 'A2065' 'A2066' 'A2067' 'A2068' 'A2069'...
'A2070' 'A2071' 'A2072' 'A2073' 'A2075' 'A2076' 'A2077' 'A2078' 'A2079'...
'A2080' 'A2083' 'A2084' 'A2085' 'A2086' 'A2088' 'A2089'...
'A2090' 'A2091' 'A2092' 'A2094' 'A2095' 'A2096' 'A2097' 'A2098' 'A2099'...
'A2101' 'A2102' 'A2103' 'A2104' 'A2105' 'A2106' 'A2108' 'A2109'...
'A2110' 'A2111' 'A2113' 'A2114' 'A2116' 'A2117' 'A2119'...
'A2120' 'A2121' 'A2122' 'A2124' 'A2125'};


for j = 1:numel(subjectname)
    %% Get data
    % Read in logfile data
    % read_logfile_auditory_linebyline is especially used for
    % mous_auditory_logfileanswers.m
    [oritxt] = read_logfile_auditory_linebyline(subjectname{j});

    % Define sentences/word lists which were proceeded by a question
    wordpresent = zeros(size(oritxt));
    for m = 1:size(oritxt,1)
        check = regexp(oritxt{m},'QUESTION \d\d\d');
        if ~isempty(check)
            wordpresent(m) = 1;
        end
    end
    %% Extract data
    % get entire row of the questions
    idx  = find(wordpresent == 1);
    resp  = oritxt(idx);
    
    % QuestionNr corresponds to sentence number (aka .wav filename)
    tmp = zeros(1,4);
    for k = 1:size(resp,1)
        questIndex = regexp(resp{k},'QUESTION \d\d\d');
        QueNr = resp{k}(questIndex+9:questIndex+11); % to only get the number
        tmp(3,k) = str2num(QueNr);

        SubnrInd = regexpi(resp{k},'A\d\d\d\d');
        subname = resp{k}(SubnrInd+1:SubnrInd+4);
        subnr = str2num(subname);
    end
    QuestionNr = transpose(tmp);

    % mark the condition (triggers) in another row
    for R = 1:length(QuestionNr)
        QuestionNr(R,1) = subnr;
        if QuestionNr(R,3) < 204
            QuestionNr(R,4) = 4;
        elseif QuestionNr(R,3) > 204 && QuestionNr(R,3) < 409
            QuestionNr(R,4) = 3; 
        elseif QuestionNr(R,3) > 501 && QuestionNr(R,3) < 704
            QuestionNr(R,4) = 2;
        elseif QuestionNr(R,3) > 705
            QuestionNr(R,4) = 1;
        end
    end
    
    
    %% Flag incorrect responses
    for m = 1:size(resp,1)
        checkincor = regexp(resp{m},'incorrect');
        if ~isempty(checkincor)
            QuestionNr(m,2) = 1;
        end
    end
    %% calculate descriptives (mean, SD)
    
    if j == 1
      subjavg = zeros(numel(subjectname),3);
    end
    
    % all questions
    wrong = sum(QuestionNr(:,2));
    allq  = size(QuestionNr,1);
    subjavg(j,1) = ((allq-wrong)/allq)*100; % percentage correct per person

    % sent
    i = find(ismember(QuestionNr(:,4),[4 3]));
    tmp = QuestionNr(i,:);
    wrong = sum(tmp(:,2));
    allq  = size(tmp,1);
    subjavg(j,2) = ((allq-wrong)/allq)*100;

    % word lists
    i = find(ismember(QuestionNr(:,4),[1 2]));
    tmp = QuestionNr(i,:);
    wrong = sum(tmp(:,2));
    allq  = size(tmp,1);
    subjavg(j,3) = ((allq-wrong)/allq)*100;
    
    %% SPSS worksheet format
    
    % 1 = number of questions
    % 2 = allcor
    % 3 = allincor
    % 4 = RCword incor  (RCword = 2)
    % 5 = RCsen incor   (RCsen  = 4)
    % 6 = MXword incor  (MXword = 1)
    % 7 = MXsen  incor  (MXsen  = 3)
    % 8 = RC word cor
    % 9 = RC sen cor
    % 10 = MX word cor
    % 11 = MX sen cor
    % 12 = subjname
    
    if j == 1
      sp = zeros(102,12);
    end
    sp(j,1) = size(QuestionNr,1);
    tmp     = sum(QuestionNr(:,2));
    sp(j,3) = tmp;
    if tmp == 0 
      sp(j,2) = size(tmp,1);
    else
      sp(j,2) = sp(j,1) - sp(j,3);
    end
    
    i = find(QuestionNr(:,4) == 2);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,4) = tmp2;
    if tmp2 == 0
      sp(j,8) = size(tmp,1);
    else 
      sp(j,8) = size(tmp,1) - sp(j,4);
    end
    
    i = find(QuestionNr(:,4) == 4);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,5) = sum(tmp(:,2));
    if tmp2 == 0
      sp(j,9) = size(tmp,1);
    else 
      sp(j,9) = size(tmp,1) - sp(j,5);
    end
    
    i = find(QuestionNr(:,4) == 1);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,6) = sum(tmp(:,2));
    if tmp2 == 0
      sp(j,10) = size(tmp,1);
    else 
      sp(j,10) = size(tmp,1) - sp(j,6);
    end
    
    i = find(QuestionNr(:,4) == 3);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,7) = sum(tmp(:,2));
    if tmp2 == 0
      sp(j,11) = size(tmp,1);
    else 
      sp(j,11) = size(tmp,1)- sp(j,7);
    end
    
    sp(j,12) = str2num(subname);
        
    %% concatenate data across subjects
    if j == 1
      SingleTrialResponse_aud_meg = QuestionNr;
    else
      SingleTrialResponse_aud_meg = [SingleTrialResponse_aud_meg;QuestionNr];
    end
    
   
end

grpdesc(1,:) = mean(subjavg);
grpdesc(2,:) = std(subjavg);

save('QuestionResponses_aud_meg_11Nov2014','SingleTrialResponse_aud_meg','subjavg','grpdesc','sp');
