% Intended functionality of this script:
%  -extract the coded wordtype

clear all;

% read the file provided by Nietzsche
%[data_num,data_txt,data_raw] = xlsread('Mous_categories.xls','','','basic'); 
[data_num,data_txt,data_raw] = xlsread('Hulpwerkwoorden MOUS-checked (without color codes).xlsx','','','basic');
% load in the stimuli struct-array
load mous_stimuli;

% the first column in data_num codes for the stimulus ids
ids = data_num(:,1);
ix  = find(isfinite(ids));
iy  = ix+1; % the next line contains the numeric data

for k = 1:numel(stimuli)
  if ~isempty(stimuli(k).id)
    stimid(k,1) = stimuli(k).id;
  end
end
for k = 1:numel(ix)
  sel = find(stimid==ids(ix(k)));
  if isempty(sel)
    continue;
  end
  tmp = data_num(iy(k),:);
  tmp_finite = isfinite(tmp);
  tmp = tmp(find(tmp_finite,1,'first'):find(tmp_finite,1,'last'));
  stimuli(sel).wordtype = tmp;
end

% sanity check for the number of coded words
ok = false(numel(stimuli),1);
for k = 1:numel(stimuli)
  if numel(stimuli(k).words)==numel(stimuli(k).wordtype)
    ok(k)=true;
  end
end

% 516, 676, and 871 are not OK.
% JM manually checked it against Laura's xls file (available on bigU)

% do a manual fix

% 516: the last word 'alweer', should get a 2
stimuli(516).wordtype(end+1) = 2;

% 676: the last word 'opa', should get a 3
stimuli(676).wordtype(end+1) = 3;

% 871: the first word vlak (with value 2) is not in the wordtype list
stimuli(871).wordtype = [2 stimuli(871).wordtype];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TO DO: identify the auxiliairy verb and code this with a 5
% THIS HAS BEEN DONE 20150126


% 'Toen de barkeeper die de irritante klant bediende wegliep gingen de deuren open'
% 'Toen de manke dronkaard die de barkeeper betaalde lachte viel de kruk om'
% 'De rector die de stoere puber strafte was erg onredelijk'
% 'De inbreker die de gekrenkte pastoor smeekte was ten einde raad'
% 'Vorige week kreeg de assistent die de bruine tanden behandelde de uitslag'
% 'Vorige maandag kreeg de medicus die de vreemde pokken behandelde zelf de pokken'
% 'Laatst kreeg de gevreesde psychiater die de verslaafde behandelde zijn ontslag'
% 'De overtreder die de smeris ontvlucht was is een kronkelig paadje ingerend'
% 'De eigenaars van het landgoed die honderden bezoekers rondleiden zijn trots'
% 'Gisteren had de brede bodyguard die de filmster beschermde een vrije dag'
% 'Morgen krijgt de ober die de beroemde president beledigde zijn ontslag'
% 'De arts die de vieze bandage verschoonde trok eerst plastic handschoenen aan'
% 'De sportarts die de hockeyer met de gescheurde pezen adviseert heeft er veel verstand van'
% 'De oma met het gebroken bekken die de verpleegster raadpleegde moest huilen'
% 'De alcoholist die de bekende psycholoog behandelde heeft weer een terugval'
% 'Maandag heeft de scholier die de meester treitert alweer punaises op de stoel gelegd'
% 'Jochem die altijd te hoog springt tijdens basketbal heeft zijn enkel bezeerd'
% 'De politieman die de agressieve kraker arresteert gaat hardhandig te werk'
% 'De staker die de angstige dames bekogelt gaat te ver'
% 'De journalist die de beroemde bondscoach interviewt wil veel weten'
% 'De zuster die de aan tuberculose lijdende bejaarde wast is zorgzaam'
% 'De goochelaar die de vrijwilliger uit het enthousiaste publiek instrueert is onduidelijk'
% 'De geduldige dominee die de baby doopt begint te spreken'
% 'De voorganger die het snoezige kleintje doopt houdt haar stevig vast'
% 'Dat meisje die de boterham zonder pindakaas wil is verwend'
% 'Robert die de schone dochter van Jan ten huwelijk vroeg slikte'
% 'De detective die criminelen opspoort krijgt een vette beloning van de staat'
% 'De speurhond die de illegale drugs opspoort krijgt een koekje'
% 'De gedetineerde die de trage bewaker afschudt krijgt hulp van zijn handlanger'
% 'Vandaag is de laatste kandidaat die de examinator overtuigt erg imponerend'
% 'De spits die de trainer opstelde had een cruciale training gemist'
% 'Niemand wist dat een gevaarlijke tornado ontstond die veel slachtoffers zou eisen'
% 'De employee die de ontsnapte dieven beschrijft is erg nauwkeurig'
% 'De wrede president die de onderdaan beveelt is boos'
% 'Het derde getal dat de oplettende toehoorder signaleert is zes'
% 'Mijn vriendin Mona is gek op jongens die gemixte drankjes kopen voor haar'
% 'Gisteren had de aannemer die de bejaarde bewoner matste een goed humeur'
% 'Het vrouwtje dat verlaten poezen opvangt heeft ruzie met de buren'
% 'Onlangs gaf de jongeman die de populaire portier inhuurde een groot feest'
% 'Het elfje dat de sterke beren betoverde was erg vriendelijk'
% 'De schilder die de knappe prinses tekent zit onder de verf'
% 'De kokkin die pap voor dakloze burgers kookt heeft geen zin meer'
% 'Nora die warme dekens voor arme mensen weeft is gelukkig'
% 'De gewelddadige schutter die jullie directeur doodde is al eerder veroordeeld geweest'
% 'De ruiter die zijn geliefde paarden streelde was de winnaar geworden'
% 'De raadsman die de wrede delinquent bijstond was op de radio'
% 'De opgesloten peuters die de ouders alarmeren zijn in paniek'
% 'De ouders die de angstige dochters bevrijden gingen opgelucht naar huis'
% 'Joost grijpt de stoere kidnapper die de bange directrice ontglipt in zijn kraag'
% 'Zijn bazin die bang is voor de starre diplomaat rent de deur uit'
% 'De opzichter die de nuchtere boswachter uitbuit is een onaardige man'
% 'De werknemer die de strenge directeur gehoorzaamt is bang zijn baan kwijt te raken'
% 'De fans die de gespannen bowlers aanmoedigen willen dat hun sporthelden winnen'
% 'Ik sprak gisteren nog met Hans die de scheve torens ontworpen heeft'
% 'Toen de zwerver die de hulpverlener hielp de bereden politie zag rende hij weg'
% 'Toen de heilsoldaat die de zieke dakloze huisvestte de kamer binnenkwam schrok hij'
% 'De grootvader die de slinkse deugniet doorhad voelde zich bedrogen'
% 'Ik schrok toen de goedkope beunhaas die het achterste bordes repareerde lachte'
% 'De judoka die de dwaze belager vloerde was niet te houden'
% 'De bedrieger die de simpele taxateur misleidde voelde zich schuldig'
% 'Mijn tante Agaat die de wedstrijd won had gladde pieren gebruikt'
% 'De naaktlopers die de mensen in het Haagse bordeel vermaken hebben het koud'
% 'De ontwerper die de koningin kleding verkoopt is erg creatief'
% 'De etaleur nam de plastic paspop die in de gang stond mee'
% 'Mijn zuster Fransien die de duurste trompet uitkiest heeft geld genoeg'
% 'De kapper die de drukke teamleider bijknipt heeft veel ervaring'
% 'Joke die de Spaanse tamboerijn speelt staat het liefst vooraan'
% 'De behulpzame serveerster die de eenvoudige boerin hielp hield netjes de deur open'
% 'In de winkel die ik zag werden hippe brillen verkocht'
% 'Het behoorlijk stugge diafragma dat buikholte en borstholte scheidt is erg belangrijk'
% 'Ik neem de boer die het kleine biggetje voert niet serieus'
% 'De puber die de kwade bazin haatte was ten einde raad'
% 'Richard die de oudere dieren verzorgde ging geld voor hen verzamelen'
% 'Vorige week kreeg de zielige bangerik die de tandarts inschakelde heftige pijn'
% 'Afgelopen maand kreeg de gewonde die een bekende paragnost inschakelde vele complicaties'
% 'De buurman van mijn zus die een heftige psychose had is beter'
% 'Ik keek naar mijn broer die de grote takken voor het vuur gebruikte'
% 'De ervaren agent die daar liep heeft de bange toerist gered'
% 'De ervaren makelaars die de nieuwe kopers rondleiden zijn gehaaid'
% 'Ik nam een lekker biertje dat gemaakt was van gerst'
% 'De oudere broer van de eigenaar die de eerste bezoekers ontving knipoogde'
% 'Mijn tante die heerlijke jam van verse bramen maakt gaat verhuizen'
% 'De jonge dief die vluchtte had haar nieuwe paspoort gestolen'
% 'De verkoper die de moderne telefoon aanprees verdiende veel geld'
% 'De orthopeed die de blessure behandelt heeft er weinig benul van'
% 'De secretaresse geeft de advocaat die de mannelijke beambte adviseert een brief'
% 'De wijze oude man die ieders dromen uitlegt komt morgen'
% 'Maandag heeft de aardige docent die de scholier onderwijst een vrije dag'
% 'Mijn groene zijden pyjama die in de kast ligt mag je lenen'
% 'Mijn kleine nichtje die jaloers is wil dit mooie potlood ook'
% 'Alleen mensen die verstand hebben van wilde honden mogen pitbulls houden'
% 'Alleen een echte taaie die doorzet krijgt een plekje op de eerste rij'
% 'Het jonge hondje van mijn buurman die de dikke duiven opjaagt is wild'
% 'Door heel scherpe bochten die in Griekenland voorkomen gebeuren veel ongelukken'
% 'De vrouw die prachtige tekeningen maakt mag vanaf dinsdag naar de kunstacademie'
% 'Sonja keek verbaasd naar moeder die de overige biscuitjes in de prullenbak gooide'
% 'De politieagent die de agressieve peetoom arresteert gaat hardhandig te werk'
% 'De agent die de snelste was had de naakte kraker gearresteerd'
% 'De reporter die de vermoeide ballerina interviewt wil veel weten'
% 'De moeder die extra dekens voor haar dochter vraagt is kansloos'
% 'De beroemdheid die de reporter wegstuurt wil de wachtende politie niet te woord staan'
% 'De clown die op het zonnige terras zit is uit op wraak'
% 'Mijn moeder verkoopt haar oude auto die geen passende trekhaak heeft'
% 'De nieuwe propellor die was besteld door de mechanicus was rood'
% 'De verpleegster verzorgt de zieke die last van ontstoken pukkels heeft'
% 'De juf berispte het jongetje dat de gammele drukknop indrukte'
% 'De overvaller stal alle kostbaarheden die de verbaasde buurman in huis had'
% 'Het belegde bruine bolletje dat op het aanrecht ligt is vers'
% 'Margriet die de drukke periode meer dan zat was ging op vakantie'
% 'Zij schrok van de schreeuw die de wilde barbaar uitbracht'
% 'Mijn aardige collega die ingedeeld was in de vroege dienst ging weg'
% 'Zonder groot protest nam het meisje dat moest huilen een hap groente'
% 'Het zeldzame plantje dat in het venster stond had water nodig'
% 'in het luxueuze banket dat net gebracht was zat een tor'
% 'Mijn knappe oom Henk die de onzekere blondine uitnodigde moest lachen'
% 'De oude agent die het verdachte pakketje ontving opende het niet'
% 'Ondanks zware tegenslag die iedereen ervaart gaan de meeste mensen gewoon door'
% 'Aan onstuimige tieners die hun gang gaan valt doorgaans weinig te doen'
% 'Mannen die een strakke bandana om hun hoofd hebben zijn stoer'
% 'Vandaag is de gevatte brunette die de zangeres beoordeelt erg partijdig'
% 'Toch is de bloemist die de geschikte sollicitant uitnodigt erg vriendelijk'
% 'De tamme poema die op de Veluwe loopt is niet gevaarlijk'
% 'Vera die het hondje wilde aaien liet de jonge puppy erg schrikken'
% 'Op de vorige pagina stond een verkeerde zin die over eendenjacht ging'
% 'De blinde typiste die ondanks haar handicap werkte wist het antwoord'
% 'De resultaten die er niet om logen lieten een sterke tendens zien'
% 'Moeder keek boos naar de kleuter die een flinke pruillip trok'
% 'Het nieuwe doelwit dat de tijger had gekozen liep het bos in'
% 'Toen de choreograaf die de trage danser uitschold de reden hoorde schrok hij'
% 'De man die de politie arresteerde werd onder immens protest afgevoerd'
% 'De flinke bonus die werd uitgedeeld aan het bestuur werd opgemerkt'
% 'De leerling die werd verhoord had de vermiste decaan vermoord'
% 'De vrouw die zwanger was werd in kritieke toestand opgenomen in het ziekenhuis'
% 'De vergeten dichter die de wrede lezer vreest is wanhopig'
% 'De beschermheer van Delhi die de heilige tempel bouwde is gestorven'
% 'Het houten bureau dat knullig in elkaar gezet was viel ineen'
% 'De magere dronkelap die de uitsmijter ontloopt heeft iets te verbergen'
% 'Een geschreven brief die in de brievenbus valt zie ik nog zelden'
% 'De ster die voldoende privacy belangrijk acht wordt vaak gebeld'
% 'De omstanders die erg kritisch zijn maken de beroemde technoloog belachelijk'
% 'De vlotte babbel die hij kan hebben tijdens sollicitaties helpt wel'
% 'Vincent die beroemde portretten geschilderd heeft kon daar helaas niks mee verdienen'
% 'De artiesten die geen werk hebben moeten de huilende babies vermaken'
% 'De route die langs de Utrechtse plassen liep was langer dan verwacht'
% 'De heks die haar een onzekere toekomst voorspelde lachte hard'
% 'Gisteren kreeg de chauffeur die het verstopte buskruit ontdekt had een beloning'
% 'De onervaren musicus die de dure zwarte piano gestemd heeft was zenuwachtig'
% 'Mijn tante die ervan hield knusse dorpjes te bezoeken was enthousiast'
% 'Op de gammele tandem die niet verzekerd was kwamen we niet ver'
% 'De Hollandse bossen die prachtig zijn bezoekt de Zwitserse man graag'
% 'Gisteren had oma die een zoete pannekoek had gegeten flinke buikpijn'
% 'Modieuze Sarah die wollen tassen op de markt bracht had succes'
% 'Het ideale breekijzer dat voor vele mannen onmisbaar is ligt in de winkels'
% 'Voor twintig dollar die minder waard zijn dan voorheen krijg je maar weinig'
% 'De staat betaalde de talentvolle advocaat die een uitstekend pleidooi had gehouden'
% 'De schone parkiet die de madam inspireert zit opgesloten in de kooi'
% 'De hevige bliksem die een kilometer verder insloeg zorgde voor brand'
% 'Mijn hondje beet zomaar in de lekkere taart die voor oma was'
% 'De corrupte bankier die goede zaken deed had geen geweten'
% 'De vastzittende kinderen die de vroege passanten alarmeren zijn in paniek'
% 'Het nieuwe project dat veel geld kost lijkt in het water te vallen'
% 'Mijn gebakken ei dat een kapotte dooier had was heerlijk'
% 'De collega's en omstanders troosten de bange techneut die huilt'
% 'De dikke darmen die van het varken afkomen zijn gevuld'
% 'De erg botte bioloog die erg kwaad keek bukte en viel'
% 'Hij struikelde over de behangrol die de onhandige behanger liet vallen'
% 'Ik haat de adviseur die onze dochter overtuigde dirigent te worden'
% 'Hij die niet wil luisteren moet nu op dikke blaren zitten'
% 'De snelle drummer die een band zocht plaatste een advertentie'
% 'Het stevige korte penseel dat de voorkeur van Joris had was weg'
% 'De fruitige dranken die soms vreemd smaakten werden geschonken op het feest'
% 'Met kromme tenen die ze niet meer recht kreeg stond ze op'
% 'Mijn broer Hans die de milde pastoor zijn vele zonden opbiechtte huilde'
% 'Opa Jan die bakker is wilde vroeger altijd piloot worden of brandweerman'
% 'Ik at de muffe toast die niet goed smaakte toch maar op'
% 'Frank werd erg nerveus van de vreemd ogende patholoog die hem onderzocht'
% 'Mijn vriendin die de pas overleden tennisser kende ging naar de begrafenis'
% 'in dat kamp voor tieners was geen enkele begeleider die verstand van zaken had'
% 'Hij redde de bejaarde die zich in de droge beschuit verslikte'
% 'De professor die vanaf zijn dertigste domino speelde had niet gewonnen'
% 'Het versleten toestel dat nog aardig goed draait moet gekeurd worden'
% 'Rosa die de prachtige bruiloft bedacht had moest huilen van vreugde'
% 'De grote bruine panda die met uitsterven bedreigd wordt rekent op u'
% 'De bands die erg populair zijn brengen enorme tenten met zich mee'
% 'De kleine gans die de andere persoon vasthield begon hard te fladderen'
% 'Ton die dit prachtige paradijs had ontdekt wilde het verborgen houden'
% 'De vers gemaakte salade die deze bedorven tomaat verpest heeft gooi ik weg'
% 'Onze verhitte discussie die op niks uitdraaide heeft weinig zin gehad'
% 'De kopers van het perceel dat een vaste bestemming had kwamen niet'
% 'Katten die continu plukjes haar verliezen kunnen een tekort aan vitamine hebben'
% 'Verse beetgare pasta die overgoten wordt met rode saus is niet te versmaden'
% 'Martine die het glimmende dressoir net gepoetst had vond een gouden ketting'
% 'Kreta dat prachtige stranden heeft is vanwege het massale toerisme veel minder aantrekkelijk'
% 'Peter die de gemene duivel had uitgedreven was doodmoe en sliep meteen'
% 'De heks die op haar kromme bezem door de lucht vloog was lelijk'
% 'Zijn opa die doorgaans borrels drinkt is tegen een boom aan gereden'
% 'De ring van moeder die een echte diamant bevat is uit huis gestolen'
% 'De oogarts van Anne die goedkope brillen aanbiedt is ook rijk geworden'
% 'Het aardige vrouwtje gaf Henk die een kleurige papegaai gekocht had een zak pitjes'
% 'De reus die de weg wees aan een kleine dwerg had een knuppel'
% 'Patricia die hard geleerd had haalde voor het moeilijke tentamen een hoog punt'
% 'De trui die in de nieuwe droger terecht was gekomen paste niet meer'
% 
% 
% 
% 'in Rotterdam hebben we samen prachtige dingen tot stand gebracht'
% 'Op een kortere termijn vertrok het gezelschap naar de bus'
% 'Lezers hebben daar in groten getale bezwaar tegen gemaakt'
% 'Het is een schrijnende situatie waaraan de Nederlandse politiek nauwelijks iets doet'
% 'De afgelopen dagen zijn politiek niet de meest succesvolle geweest'
% 'Ook in Nederland staat het strenge toezicht op accountants ter discussie'
% 'Dit zijn geen regionale problemen zoals die op de Antillen'
% 'Niet alle pillen en blauwe poeders kunnen zonder meer worden ingevoerd'
% 'Je haalt zo het complete bouwsel uit zijn verband'
% 'Vorig jaar zijn deze dertig dossiers allemaal aan elkaar gekoppeld'
% 'De actiegroep signaleert een nieuw probleem voor de natuur in Waterland'
% 'in de laatste race eindigde het olympisch paard als derde'
% 'Bij het openbare debat werd iedereen duidelijk wat de bedoeling was'
% 'Hij werkt voor twaalf dollar per uur bij die winkel'
% 'Hij gaf zijn eigen bestaan op voor zijn bruid in India'
% 'Groeperingen binnen de kerk bestrijden zijn grote bekendheid en macht'
% 'Het is een minder tijdrovende procedure dan klassieke animatie'
% 'De drukke pubers in mijn straat zorgen voor veel overlast'
% 'Het bruine broodje is belegd met kaas en verse ham'
% 'Meer dan duizend arbeiders werken in het moderne bedrijf tegenover het station'
% 'Anke geeft de groene plant wat water met een gieter'
% 'De wijnglazen staan op de bovenste plank in het keukenkastje'
% 'De moedige trimmers bereikten eindelijk de top van de berg'
% 'De man maakte een diepe buiging voor de nieuwe koningin'
% 'De huishoudster nam de tafel af met een vochtig doekje om het stof te verwijderen'
% 'De zakenvrouw droeg een mooie grijze pantalon tijdens de voorstelling'
% 'De Keukenhof wordt jaarlijks druk bezocht door buitenlandse toeristen met dure fotocamera's'
% 'De auto moest naar de garage voor een grote beurt en een periodieke keuring'
% 'Kees kocht voor zijn vrouw een keurig bosje bloemen en een doos bonbons'
% 'in het sprookje zit de koning altijd op zijn gouden troon te niksen'
% 'De schilder kleurde de details in met een klein penseel van varkenshaar'
% 'Dorien werd helemaal gek van de druppende kraan in de keuken'
% 'De firma viert haar tienjarig bestaan met een gigantisch feest'
% 'Het zieke meisje had flinke koorts door de griep'
% 'Ik hielp de lastige klant geduldig met zijn eerste bestelling'
% 'Op kantoor gebruiken ze voor simpel kopieerwerk uitsluitend ongekleurd papier voor een beter milieu'
% 'Marco gaat ieder half jaar bij zijn eigen tandarts op controle'
% 'De bloemist bezorgde bij Lisa een prachtig boeket rode rozen'
% 'Floor had vannacht een hele angstige droom over slangen'
% 'De twee auto's waren betrokken bij een frontale botsing op de gevaarlijke autoweg'
% 'De eigenaar van het moderne theater beschuldigde de vrouw van diefstal'
% 'Om niet herkend te worden droeg de overvaller een blonde pruik met krullen'
% 'De zanger trad op voor een groot publiek in Ahoy'
% 'Die boer loopt nog op ouderwetse klompen door het boerendorp'
% 'Sinds Dorien's tante hier op bezoek was is er veel veranderd'
% 'in de wieg lag een baby met gebalde knuistjes lekker te slapen'
% 'Bij het spelen lette het orkest goed op kleine bewegingen van de dirigent'
% 'na de verkiezingen was de PvdA de grootste partij van Nederland'
% 'Waarschijnlijk maken duiven de grootste rotzooi op het centrale plein'
% 'Spanje is erg in trek vanwege het gunstige klimaat en de prachtige stranden'
% 'Tegenwoordig juichen kinderen alleen nog voor grote verrassingen op hun verjaardag'
% 'Ondanks dat er kleine danspasjes werden gemaakt struikelde Roos over haar voeten'
% 'De bouw van het schuurtje bleek nog een behoorlijk karwei voor Hans'
% 'De minister was benieuwd naar het totale percentage van de kiezers in Friesland'
% 'Het meisje moest van haar nieuwe tandarts een beugel tot haar achttiende'
% 'Het verloofde koppel bekijkt de locatie voor hun bruiloft in juni'
% 'Er waren veel artsen in de stad vanwege een belangrijke bespreking over chirurgie'
% 'Op zijn werk drinkt Peter heel wat koffie met suiker'
% 'De botsing vond plaats op een riskante kruising net buiten de stad'
% 'De terrorist bracht de politie op een vervelend dwaalspoor door van auto te wisselen'
% 'De schildwacht stond uren bij de poort van een vervallen kasteel op de uitkijk'
% 'We maakten een grote kring om samen te zingen'
% 'Vanwege het stormachtige weer spelen meerdere teams in een sporthal'
% 'Halverwege de spannende wedstrijd houden de agenten een aantal vechtende pubers aan'
% 'Aan het maken van reclame besteden lucratieve bedrijven veel geld'
% 'Voor de aankoop van een auto sluiten mijn nieuwe buren een lening af'
% 'Vanwege de massale stakingen in het slachthuis stijgen de huidige prijzen van het vlees'
% 'Bij de aankoop van twaalf flessen wijn krijgen de rijke toeristen een fles cadeau'
% 'Onder de eeuwenoude eik in de tuin bloeien de witte tulpen volop'
% 'Bij de opening van de nieuwe sporthal kregen de talrijke bezoekers een consumptie'
% 'Tijdens de heftige discussie stellen de gedreven advocaten lastige vragen'
% 'Vanwege het onlangs behaalde diploma trakteren mijn vrienden op gebak'
% 'Tijdens de rumoerige bespreking beslisten de leden de staking voort te zetten'
% 'Tot ergernis van de strenge beheerder gooien de tieners rotzooi op het terrein'
% 'Vanwege de enorme behoefte aan ijslollies voert de fabrikant de productie op'
% 'Alleen ervaren duikers springen vanaf de hoge duikplank in het zwembad'
% 'De gruwelijk verwende tieners kopen een ketting van goud'
% 'Zowel de leerlingen als de bezorgde docenten bidden voor de doodzieke rector'
% 'De in lompen gehulde bedelaar steelt fruit van de groenteboer'
% 'De vrolijke meisjes dansen tijdens de gezellige braderie uitgelaten met elkaar'
% 'De vermoeide feestgangers rusten na de vrolijke bruiloft uit in het park'
% 'De lachwekkende clowns vermaken met talloze dwaasheden het laaiend enthousiaste publiek'
% 'De behoorlijk dronken bestuurder verzint een flauw smoesje voor de politieman'
% 'De vrolijke ober serveert fel gekleurde drankjes met kokosnoten en ananassen'
% 'De goede vriend bedenkt een toepasselijk gedicht om het kersverse bruidspaar te verrassen'
% 'De gevaarlijke overvallers nemen met een handvol diamanten geen genoegen'
% 'in indische restaurants wordt pikant vlees vaak met groene pepers geserveerd'
% 'De oudere man leest de zondagse krant in de huiskamer'
% 'De pientere dame kreeg een prachtig boekje voor haar verjaardag'
% 'De knappe ober presenteert het lopend buffet op het terras'
% 'Kinderen in China naaien goedkope kleren voor westerse consumenten'
% 'Hij maakte de verstandige keuze om vlug naar huis te vertrekken'
% 'Een heftige drang om te spijbelen overvalt me al meteen'
% 'Van de drie vocalisten maakte Karin de meeste indruk'
% 'Ook bij de Nederlandse dijken is een dergelijk probleem vastgesteld'
% 'Ik kom net terug uit de heropende dierentuin in Amsterdam'
% 'Op dat moment liet haar eigen broertje de hond uit'
% 'Ook dat kleine dorpje wordt nu bedreigd door de nieuwbouw'
% 'Op die goede prestatie was helemaal niets af te dingen'
% 'De vroegere afhankelijke positie past het veranderde Griekenland niet meer'
% 'Over enkele jaren breekt het onnodige drama pas goed los'
% 'Een belangrijk probleem is de vraag naar meer goedkope grondstoffen'
% 'De naam van de huidige president kon hij niet noemen'
% 'Alleen in ons eigen bedrijf geldt de verlaging voor reparaties'
% 'Bij het komende congres willen ze dat goede bestuur weer terug'
% 'Zijn houding lijkt hem vanaf het vroege begin te zijn ingegeven'
% 'Soms hebben we alle vertrouwen in de Nederlandse politiek verloren'
% 'Zelfs een grove dwaling zorgde niet voor een mentale inzinking'
% 'Het besluit gaat over de voorgenomen destructie van de kerncentrale in Dodewaard'
% 'De betere behuizing is afgedwongen door de nieuwe Europese regels'
% 'Wanneer krijgt die lakse puber nu eindelijk eens zijn diploma'
% 'Dat kleine perceel was op een of andere manier het meest geliefd'
% 'Ook de vermoeide troepen in het gebied werden nog verder uitgebreid'
% 'in de jaren zeventig trok het boeiende programma miljoenen luisteraars'
% 'Vele duizenden bezoekers uit de hele wereld komen naar het popconcert'
% 'Dat mooie bericht gaat over het nieuwe en eeuwige Jeruzalem'
% 'De koning en zijn trouwe dienaren doen er niet toe'
% 'Van de eisende partij moest de malafide makelaar zijn bedrijf sluiten'
% 'Ik lees graag mooie boeken in mijn vrije tijd'
% 'Vanwege zijn eigen bekentenis wordt hij veroordeeld voor de moord'
% 'Helaas dreef de machtige directeur zijn zin door bij zijn personeel'
% 'Het was een prachtige derde overwinning op Hawaii in drie jaar tijd'
% 'Hopelijk zien we de beroemde tekeningen wel snel weer terug'
% 'Het arbeidsethos is in centraal Bolivia heel anders dan in het zuiden'
% 'Een paar mensen doen er alles aan om het populaire boekje te bemachtigen'
% 'Vandaar dat kippen zich op hun magere pootjes staande houden'
% 'De beruchte daders meldden zich zelf bij de politie'
% 'Op de tweede dinsdag ging het echter bijna mis'
% 'Er komt een nationaal bestuur om de bureaucratie te bestrijden'
% 'in Japan en China komt een geringe deflatie op gang'
% 'Na die fout stortte de complete ploeg in elkaar'
% 'Het zachte klimaat hield aan tot bijna halverwege de maand'
% 'Vanwege de jonge plantjes zit de plastic emmer vol met aarde'
% 'De hond kwam aanlopen met een plastic diadeem in zijn bek'
% 'Natasja stopte de zakdoek in haar nieuwe broek met ruches'
% 'Overtreders van de wet kunnen hier rekenen op een eerlijk proces met een onpartijdige rechter'
% 'Na een avondje stappen had de vrolijke bakker een behoorlijke kater van de alcohol'
% 'De student kwam niet rond van zijn karige beurs van vierhonderd gulden'
% 'Na het uitvallen van de elektriciteit verlichtte Carolien haar gezellige terras met kaarsen en lampionnen'
% 'De barones nodigde een aantal gasten uit voor een heerlijk diner met dure wijnen'
% 'De handen van de moordenaar zaten onder het druipende bloed van het slachtoffer'
% 'Het volleybalteam won met de eerste plaats een grote beker gevuld met champagne'
% 'Het vrouwtje veegde de vloer met een stokoude bezem gemaakt van twijgen'
% 'in het kantoor stond de vrouw bij de drukke balie voor de aangiftes'
% 'De deftige pakjes van oma worden op zolder bewaard in een grote kist van eikenhout'
% 'De toneelbouwers waren erg tevreden met hun mooie decor voor het drama'
% 'Op zijn zestiende verjaardag kreeg de puber een stoere brommer en een helm cadeau'
% 'De auto kwam langs de snelweg stil te staan zonder brandstof in de tank'
% 'De toeristen hadden veel moeite met het opzetten van hun kleine tentje tijdens de storm'
% 'De aardige docent heeft dit jaar een erg rustige klas om les aan te geven'
% 'opa klopte de zwarte tabak uit zijn pijp in de asbak'
% 'De vakkundige tandarts trok bij Nico zijn achterste kies met de ontstoken wortels'
% 'Tijdens de vliegreis mocht het jongetje bij de ervaren piloot in de cockpit kijken'
% 'Aan het einde van de dag gaat de mobiele telefoon voor de overdracht'
% 'Oma gaat nog steeds iedere donderdag naar de kerk voor de ochtendmis'
% 'De lange bokser woog negentig kilo schoon aan de haak'
% 'De brute beroving werd vastgelegd door een verborgen camera boven de ingang'
% 'Midden in de stationshal hangt een grote poster met een zilveren lijst'
% 'De winst van die verkoper is erg hoog vanwege zijn vlotte babbel over zijn producten'
% 'De basketballers werden vanaf de kleine tribune begeleid door hun coach en trainer'
% 'Vader zit altijd aan het hoofd van de rechte tafel tijdens het avondeten'
% 'De waarzegster voorspelde mijn bijgelovige tante de toekomst met een glazen bol'
% 'De atleet werd beschuldigd van het gebruik van illegale doping vlak voor de wedstrijd'
% 'De schat werd van de zeebodem naar boven gehaald door drie ervaren duikers uit Duitsland'
% 'De gemene dader bewaart zijn goudvoorraad in een kluis onder de grond'
% 'Als avondeten eet ons gezin meestal pasta met een lekkere saus'
% 'Naar aanleiding van de melding kreeg de fanatieke politie een anonieme tip over de dader'
% 'Bram kon wel door de grond zakken na die enorme blunder van gistermiddag'
% 'Ivo kreeg op zijn werk een strenge berisping van zijn baas over zijn slechte advies'
% 'Ria gaat in de avonduren vaak lekker tennissen met een vriendin'
% 'Met mooi weer lag ik graag te zonnen op het mooie terras van het huis'
% 'Voor het chique dineetje goot Inge de wijn over in een karaf van kristal'
% 'Na het breken van de antieke vaas toonden de kinderen weinig berouw aan hun oma'
% 'Na jaren voor iemand anders gewerkt te hebben startte Luuk zijn eigen bedrijf in Eindhoven'
% 'De voorzitter werd door het voltallige bestuur ontslagen wegens wangedrag'
% 'Door de wind vallen de dorre bladeren in het zwembad'
% 'Ondanks de inspanning van de arbeider werd het belangrijke project niet afgerond'
% 'Na afloop van het gezellige feest bellen de vrolijke dames een taxi'
% 'Met de buitenlandse werknemers zoekt de arrogante directeur nauwelijks contact'
% 'In de verre toekomst reizen de mensen wellicht per vliegende schotel'
% 'Naar aanleiding van de boeiende toespraak over toenemend vandalisme leveren de studenten commentaar'
% 'Vrolijk spelend op hun paarse trommels liepen de leerlingen naar school'
% 'De gasten vertrokken omdat de lakse bediende zeer onbeleefd was'
% 'Tijdens de zeer zware training liepen de soldaten gebukt onder touwen door'
% 'Tijdens de eerste pauze kopen de scholieren vaak iets lekkers in de kantine'
% 'Aan het einde van ieder schooljaar logeren de trouwe dochters bij hun oma'
% 'Met in iedere hand een lekker dropje liepen de zusjes naar school'
% 'in die vrijstaande boerderij met royale achtertuin wonen de kennissen van mijn schoonzus'
% 'Om de lekkages in de oude kerk te verhelpen zoekt de vrome dominee een loodgieter'
% 'Voor de voornaamste resultaten van het onderzoek kun je de bekende publicatie raadplegen'
% 'Tijdens de reis door de jungle zien de rijke toeristen een groep apen'
% 'Bij het zien van het vieze beest raken de moeders helemaal overstuur'
% 'in de kleine zaal van het hotel vieren onze aardige buren hun verjaardag'
% 'Na een zware tocht door de bergen bereiken de wandelaars de camping'
% 'Mede dankzij de uitstekende organisatie komen de jonge bezoekers in groten getale'
% 'Toen de gemene dictator arriveerde schreeuwden de burgers leuzen van protest'
% 'in de moderne drogist betalen de meeste klanten uitsluitend elektronisch'
% 'De blije jongeren zorgen voor intens plezier in hun woonplaats'
