% This script extracts the SubjectName, QuestionNr and responses logfiles
% generated by presentation in the fMRI and MEG scans for stimuli presented
% in the visual domain

% Output matrix [SingleTrialResponse_vis_meg] has the following columns
% 1  subj
% 2  response (1 = wrong, 0 = correct)
% 3  sentence (.wav filename)
% 4  sentence type (RCsent, MXsent, RCseq, MXseq)
% sentence type:   1 = sentRC;  2 = sentMX, 3 = sequenceRC, 4 = sequenceMX

% Output matrix [grpdesc] holds the mean and standard deviation for all
% sentences (i.e. all sentence types) across subjects

% output matrix [sp] sorts data into the 4 types of sentences (see
% description in code) to be used for further analysis in SPSS

% not the most efficient script, but it is accurate

% nielam 14.10.2014

%% Get responses for single trials
subjectname = {'V1001',	'V1002',	'V1003',	'V1004',	'V1005',	'V1006',	'V1007',	'V1008',	'V1009',	'V1010',...
            'V1011',	'V1012',	'V1013',	'V1015',	'V1016',	'V1017',	'V1019',	'V1020',...
            'V1022',	'V1024',	'V1025',	'V1026',	'V1027',	'V1028',	'V1029',	'V1030',...
            'V1031',	'V1032',	'V1033',	'V1034',	'V1035',	'V1036',	'V1037',	'V1038',	'V1039',	'V1040',...
            'V1042',	'V1044',	'V1045',	'V1046',	'V1048',	'V1049',	'V1050',...
            'V1052',	'V1053',	'V1054',	'V1055',	'V1057',	'V1058',	'V1059',...
            'V1061',	'V1062',	'V1063',	'V1064',	'V1065',	'V1066',	'V1068',	'V1069',	'V1070',...
            'V1071',	'V1072',	'V1073',	'V1074',	'V1075',	'V1076',	'V1077',	'V1078',	'V1079',	'V1080',...
            'V1081',	'V1083',	'V1084',	'V1085',	'V1086',	'V1087',	'V1088',	'V1089',	'V1090',...
            'V1092',	'V1093',	'V1094',	'V1095',	'V1097',	'V1098',	'V1099',	'V1100',...
            'V1101',	'V1102',	'V1103',	'V1104',	'V1105',	'V1106',	'V1107',	'V1108',	'V1109',	'V1110',...
            'V1111',	'V1113',	'V1114',	'V1115',  'V1116',  'V1117'};

% For each subject, extract questions from logfile and determine
% correct/incorrect responses

for j = 1:numel(subjectname)
    %% Get data
    % Read in logfile data 
    [oritxt] = read_logfile_visual(subjectname{j});

    % Define sentences/word lists which were proceeded by a question
    wordpresent = zeros(size(oritxt));
    for m = 1:size(oritxt,1)
        check = regexp(oritxt{m},'QUESTION \d\d\d');
        if ~isempty(check)
            wordpresent(m) = 1;
        end
    end
    %% Extract data
    % get entire row of the questions
    idx  = find(wordpresent == 1);
    resp  = oritxt(idx);
    
    %% QuestionNr corresponds to sentence number (aka .wav filename)
    tmp = zeros(1,4);
    for k = 1:size(resp,1)
        qidx = regexp(resp{k},'QUESTION \d\d\d');
        % retrieve only number
        QueNr = resp{k}(qidx+9:qidx+11); 
        tmp(3,k) = str2num(QueNr);

        subnr = str2num(subjectname{j}(2:5));
    end
    QuestionNr = transpose(tmp);

    % mark the condition (triggers) in column 4
    for R = 1:length(QuestionNr)
        QuestionNr(R,1) = subnr;
        if QuestionNr(R,3) < 204
            QuestionNr(R,4) = 4;
        elseif QuestionNr(R,3) > 204 && QuestionNr(R,3) < 409
            QuestionNr(R,4) = 3;
        elseif QuestionNr(R,3) > 501 && QuestionNr(R,3) < 704
            QuestionNr(R,4) = 2;
        elseif QuestionNr(R,3) > 705
            QuestionNr(R,4) = 1;
        end
    end
    
    %% Flag incorrect responses
    for m = 1:size(resp,1)
        checkincor = regexp(resp{m},'incorrect');
        if ~isempty(checkincor)
            QuestionNr(m,2) = 1;
        end
    end
    
    %% calculate descriptives (mean, SD)
    if j == 1
      subjavg = zeros(numel(subjectname),3);
    end
    % all questions
    wrong = sum(QuestionNr(:,2));
    allq  = size(QuestionNr,1);
    subjavg(j,1) = ((allq-wrong)/allq)*100; % percentage correct per person

    % sent
    i = find(ismember(QuestionNr(:,4),[4 3]));
    tmp = QuestionNr(i,:);
    wrong = sum(tmp(:,2));
    allq  = size(tmp,1);
    subjavg(j,2) = ((allq-wrong)/allq)*100;

    % word lists
    i = find(ismember(QuestionNr(:,4),[1 2]));
    tmp = QuestionNr(i,:);
    wrong = sum(tmp(:,2));
    allq  = size(tmp,1);
    subjavg(j,3) = ((allq-wrong)/allq)*100;
    
    %% calculate descriptives (mean, SD)
    
    if j == 1
      subjavg = zeros(numel(subjectname),3);
    end
    
    % all questions
    wrong = sum(QuestionNr(:,2));
    allq  = size(QuestionNr,1);
    subjavg(j,1) = ((allq-wrong)/allq)*100; % percentage correct per person

    % sent
    i = find(ismember(QuestionNr(:,4),[4 3]));
    tmp = QuestionNr(i,:);
    wrong = sum(tmp(:,2));
    allq  = size(tmp,1);
    subjavg(j,2) = ((allq-wrong)/allq)*100;

    % word lists
    i = find(ismember(QuestionNr(:,4),[1 2]));
    tmp = QuestionNr(i,:);
    wrong = sum(tmp(:,2));
    allq  = size(tmp,1);
    subjavg(j,3) = ((allq-wrong)/allq)*100;
    
    %% SPSS worksheet format
    
    % 1 = number of questions
    % 2 = allcor
    % 3 = allincor
    % 4 = RCword incor  (RCword = 2)
    % 5 = RCsen incor   (RCsen  = 4)
    % 6 = MXword incor  (MXword = 1)
    % 7 = MXsen  incor  (MXsen  = 3)
    % 8 = RC word cor
    % 9 = RC sen cor
    % 10 = MX word cor
    % 11 = MX sen cor
    % 12 = subjname
    
    if j == 1
      sp = zeros(102,12);
    end
    sp(j,1) = size(QuestionNr,1);
    tmp     = sum(QuestionNr(:,2));
    sp(j,3) = tmp;
    if tmp == 0 
      sp(j,2) = size(tmp,1);
    else
      sp(j,2) = sp(j,1) - sp(j,3);
    end
    
    i = find(QuestionNr(:,4) == 2);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,4) = tmp2;
    if tmp2 == 0
      sp(j,8) = size(tmp,1);
    else 
      sp(j,8) = size(tmp,1) - sp(j,4);
    end
    
    i = find(QuestionNr(:,4) == 4);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,5) = sum(tmp(:,2));
    if tmp2 == 0
      sp(j,9) = size(tmp,1);
    else 
      sp(j,9) = size(tmp,1) - sp(j,5);
    end
    
    i = find(QuestionNr(:,4) == 1);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,6) = sum(tmp(:,2));
    if tmp2 == 0
      sp(j,10) = size(tmp,1);
    else 
      sp(j,10) = size(tmp,1) - sp(j,6);
    end
    
    i = find(QuestionNr(:,4) == 3);
    tmp = QuestionNr(i,:);
    tmp2 = sum(tmp(:,2));
    sp(j,7) = sum(tmp(:,2));
    if tmp2 == 0
      sp(j,11) = size(tmp,1);
    else 
      sp(j,11) = size(tmp,1)- sp(j,7);
    end
    
    sp(j,12) = subnr;
        

    %% concatenate data across subjects
    if j == 1
        SingleTrialResponse_vis_meg = QuestionNr;
    else
        SingleTrialResponse_vis_meg = [SingleTrialResponse_vis_meg;QuestionNr];
    end
end

grpdesc(1,:) = mean(subjavg);
grpdesc(2,:) = std(subjavg);

save('QuestionResponses_vis_meg_11Nov2014','SingleTrialResponse_vis_meg','subjavg','grpdesc','sp');